version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=vna_tracking
      - MONGO_PASSWORD=vna_tracking
      - MONGO_DATABASE=vna_tracking
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example