version: '3.9'
services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST='mongo'
      - MONGO_PORT='27017'
      - MONGO_USERNAME='vna_tracking'
      - MONGO_PASSWORD='vna_tracking'
      - MONGO_DATABASE='vna_tracking'
    depends_on:
      - 'mongodb'
  mongodb:
    image: 'mongo:5.0'
    container_name: 'mongo'
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example